config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  namespace :admin do
    resources :users , only: [:index, :show, :edit, :update, :destroy]
    resources :schedules, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :apply_paids, only: [:index, :show, :update]
  end
  namespace :public do
    resources :schedules, only: [:index, :show]
    resources :apply_paids, only: [:new, :index, :create, :show, :destroy]
    resources :users , only: [:index, :show, :edit, :update, :destroy]
  end
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
end

app/models/apply_paid.rb
class ApplyPaid < ApplicationRecord
  belongs_to :user
  belongs_to :schedule, optional: true
  enum apply_status: {waiting: 0, permited: 1, denied: 2}
  enum reason: {私用のため: 0, 体調不良: 1, その他: 2 }

  def get_color

    if self.apply_status_before_type_cast == 0
      #緑
      color = "#f0fff0"
    elsif self.apply_status_before_type_cast == 1
      color = "#adff2f"
    elsif self.apply_status_before_type_cast == 2
      color = "#ffff00"
    end
    color
  end

end

app/controllers/admin/apply_paids_controller.rb
class Admin::ApplyPaidsController < ApplicationController
  def index
    @apply_paid = ApplyPaid.all
  end

  def show
    @apply_paid = ApplyPaid.find(params[:id])
  end

  def update
    @apply_paid = ApplyPaid.find(params[:id])
    #binding.pry
    if @apply_paid.update(apply_paid_params)
      redirect_to admin_apply_paids_path
    else
      render :show
    end
  end

  def apply_paid_params
    params.require(:apply_paid).permit(:apply_status)
  end

end

app/helpers/admin/apply_paid_helper.rb
module Admin::ApplyPaidHelper
end

app/views/admin/apply_paids/index.html.erb
<div class="container px-4 px-sm-0 ">
 <div class="row">
  <div class="col-4 mx-3 mt-3">
      <h2>有給申請</h2>
  </div>
 </div>
 <div class="row">
     <div class="col">
     <%#= link_to "＋", new_admin_schedule_path, class: "btn shadow-sm btn-outline-secondary rounded-circle" %>
     </div>
 </div>
  <div class="row">
    <div class="col-10 mt-4">
    <%= month_calendar events: @apply_paid do |date, apply_paids| %>
        <div style="background-color: <%= apply_paids.first&.get_color %>">
            <%= date.day %>
            <ul>
            <% apply_paids.each do |apply_paid| %>
                <%= link_to admin_apply_paid_path(apply_paid.id), class:"text-dark" do %>
                  <li><%= apply_paid.user.name %>：<%= apply_paid.apply_status_i18n %></li>
                <% end %>
            <% end %>
            </ul>
        </div>
    <% end %>
    </div>
   </div>
  </div>

app/views/admin/apply_paids/show.html.erb
<div class="container px-4 px-sm-0 ">
  <div class="row">
    <div class="col-3 mx-3 mt-3">
      <h2>有給詳細</h2>
    </div>
    </div>
    <div class="row">
      <div class="my-3 mx-auto p-5 col-4">
       <table class="table table-borderless">
       <tr>
       <th>申請者</th>
       <td><%= @apply_paid.user.name %></td>
       </tr>
    　 <tr>
       <th>申請理由</th>
       <td><%= @apply_paid.reason %></td>
       </tr>
       <tr>
       <th>状況</th>
       <td><%= @apply_paid.apply_status_i18n %></td>
       </tr>
       <tr>
         <th>申請状況</th>
         <td>
          <%= form_with model: [:admin, @apply_paid], method: :patch, local: true do |f| %>
          <%#= f.select :apply_status,ApplyPaid.apply_statuses, selected: ApplyPaid.apply_statuses[@apply_paid.apply_status] %>
              <%= f.select :apply_status, ApplyPaid.apply_statuses.keys.map {|k| [I18n.t("enums.apply_paid.apply_status.#{k}"), k]} %>
          <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
         </td>
       </tr>
     </table>
     </div>
   </div>
</div>