config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  namespace :admin do
    resources :users , only: [:index, :show, :edit, :update, :destroy]
    resources :schedules, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :apply_paids, only: [:index, :show, :update]
  end
  namespace :public do
    resources :schedules, only: [:index, :show]
    resources :apply_paids, only: [:new, :index, :create, :show, :destroy]
    resources :users , only: [:index, :show, :edit, :update, :destroy]
  end
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  enum event_status: {
      出勤日（申請可）: 0,
      出勤日（申請困難）: 1,
      出勤日（申請不可）: 2,
      休日: 3,
      有給推奨日: 4
  }
  def get_color

    if self.event_status_before_type_cast == 0
      #緑
      color = "#f0fff0"
    elsif self.event_status_before_type_cast == 1
      color = "#ffff00"
    elsif self.event_status_before_type_cast == 2
      color = "#800000"
    elsif self.event_status_before_type_cast == 3
      color = "#adff2f"
    elsif self.event_status_before_type_cast == 4
      color = "#00ffff"
    end
    color
  end

  has_many :apply_paids
  has_many :user

end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < ApplicationController
  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:notice] = "新しい予定を追加しました"
      redirect_to admin_schedules_path
    else
      @schedule = Schedule.all
      render :index
    end
  end

  def index
    @schedules = Schedule.all

  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      redirect_to admin_schedules_path
    else
      render :edit
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to admin_schedules_path, notice: "削除しました"
  end

  private

  def schedule_params
    params.require(:schedule).permit(:event_name, :start_time, :end_time, :event_status, :schedule_id)
  end
end

app/helpers/admin/schedule_helper.rb
module Admin::ScheduleHelper
end

app/views/admin/schedules/edit.html.erb
<div class="container px-4 px-sm-0">
    <div class="row">
    <div class="col-3 mx-3 mt-3">
      <h2>予定編集</h2>
    </div>
    </div>
  <div class="row">
    <div class="col-10 text-center mt-4">
      <table class="table table-borderless">
       <%= form_with(model: [:admin, @schedule], local: true) do |form| %>
       <tr>
       <th><%= form.label :予定名 %></th>
       <td><%= form.text_field :event_name %></td>
       </tr>
       <tr>
       <th><%= form.label :"開始日" %></th>
       <td><%= form.date_select :start_time %></td>
       </tr>
       <tr>
       <th><%= form.label :"終了日" %></th>
       <td><%= form.date_select :end_time %></td>
       </tr>
       <tr>
         <th><%= form.label :"オプション" %></th>
         <td><%= form.select :event_status,Schedule.event_statuses.map{|k, v| [k, k]}, selected: Schedule.event_statuses[@schedule.event_status] %></td>
       </tr>
       <tr>
         <th></th>
         <td>
         <%= form.submit "保存する", class:"btn btn-primary" %>
         </td>
       </tr>
       <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/schedules/index.html.erb
<div class="container px-4 px-sm-0 ">
 <div class="row">
  <div class="col-3 mx-3 mt-3">
      <h2>Schedule</h2>
  </div>
 </div>
 <div class="row">
     <div class="col mt-3">
     <%= link_to "スケジュールを追加する", new_admin_schedule_path, class: "btn shadow-sm btn-outline-dark" %>
     </div>
 </div>
  <div class="row">
    <div class="col-9 mt-3">
    <%= month_calendar events: @schedules do |date, schedules| %>
        <div style="background-color: <%= schedules.first&.get_color %>">
            <%= date.day %>
            <ul>
            <% schedules.each do |schedule| %>

                <%= link_to admin_schedule_path(schedule), class:"text-dark" do %>
                  <li><%= schedule.event_name %></li>
                <% end %>
            <% end %>

            </ul>
        </div>
    <% end %>
    </div>
 </div>
</div>

app/views/admin/schedules/new.html.erb
<div class="container px-4 px-sm-0">
    <div class="row">
    <div class="col-3 mx-3 mt-3">
      <h2>予定登録</h2>
    </div>
    </div>
  <div class="row">
    <div class="col-10 text-center mt-4">
      <table class="table table-borderless">
       <%= form_with(model: [:admin, @schedule], local: true) do |form| %>
       <tr>
       <th><%= form.label :予定名 %></th>
       <td><%= form.text_field :event_name %></td>
       </tr>
       <tr>
       <th><%= form.label :"開始日" %></th>
       <td><%= form.date_select :start_time %></td>
       </tr>
       <tr>
       <th><%= form.label :"終了日" %></th>
       <td><%= form.date_select :end_time %></td>
       </tr>
       <tr>
         <th><%= form.label :"オプション" %></th>
         <td><%= form.select :event_status,Schedule.event_statuses.map{|k, v| [k, k]}, selected: Schedule.event_statuses[@schedule.event_status] %></td>
       </tr>
       <tr>
         <th></th>
         <td>
         <%= form.submit "保存する", class:"btn btn-primary" %>
         </td>
       </tr>
       <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/schedules/show.html.erb
<div class="container px-4 px-sm-0 ">
  <div class="row">
    <div class="col-3 mx-3 mt-3">
      <h2>予定詳細</h2>
    </div>
    </div>
    <div class="row">
      <div class="my-3 mx-auto p-5 col-4">
       <table class="table table-borderless">
       <tr>
       <th>予定名</th>
       <td><%= @schedule.event_name %></td>
       </tr>
       <tr>
       <th>状況</th>
       <td><%= @schedule.event_status %></td>
       </tr>
       <tr>
       </tr>
     </table>
     </div>
   </div>
   <div class="row">
   <div class="col text-center">
     <%= link_to "編集する", edit_admin_schedule_path(@schedule), class: 'btn btn-success px-3 mx-auto' %>
     <%= link_to "削除する", admin_schedule_path(@schedule), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger px-3 mx-5' %>
   </div>
   </div>
</div>