config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  namespace :admin do
    resources :users , only: [:index, :show, :edit, :update, :destroy]
    resources :schedules, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :apply_paids, only: [:index, :show, :update]
  end
  namespace :public do
    resources :schedules, only: [:index, :show]
    resources :apply_paids, only: [:new, :index, :create, :show, :destroy]
    resources :users , only: [:index, :show, :edit, :update, :destroy]
  end
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :paid, dependent: :destroy
  has_many :apply_paids, dependent: :destroy
  has_many :schedules, dependent: :destroy


  accepts_nested_attributes_for :paid


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :email, :day)

  end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/views/admin/users/edit.html.erb
<div class="container px-4 px-sm-0">
    <div class="row">
    <div class="col-3 mx-3 mt-3">
      <h2>登録情報編集</h2>
    </div>
    </div>
  <div class="row">
    <div class="col-10 text-center mt-4">
      <table class="table table-borderless">
       <%= form_with(model: [:admin, @user], local: true) do |form| %>
       <tr>
       <th><%= form.label :"名前" %></th>
       <td><%= form.text_field :name %></td>
       </tr>
       <tr>
       <th><%= form.label :"メールアドレス" %></th>
       <td><%= form.email_field :email %></td>
       </tr>

       <tr>
         <th><%= form.label :"有給付与日数" %></th>
         <td><%= form.number_field :day %></td>
       </tr>
       <tr>
         <th></th>
         <td>
         <%= form.submit "保存する", class:"btn btn-primary" %>
         </td>
       </tr>
       <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container px-5 px-sm-0 ">
 <div class="row">
  <div class="px-4 mx-4 mt-2 ">
  <h3>社員一覧</h3>
  </div>
 </div>
 <div class="row">
  <div class="col-8 mx-auto mt-4">

    <table class="table table-border">
     <thead>
       <tr>
         <th class="table-active">社員ID</th>
         <th class="table-active">氏名</th>
         <th class="table-active">メールアドレス</th>
       </tr>
     </thead>
     <tbody>
      <% @users.each do |user| %>
       <tr>
         <td><%= user.id %></td>

         <td><%= link_to user.name, admin_user_path(user), class: "text-dark" %></td>

         <td><%= user.email %></td>

       </tr>
      <% end %>
     </tbody>
    </table>

  </div>
 </div>
</div>

app/views/admin/users/show.html.erb
<div class="container px-5 px-sm-0 ">
 <div class="row">
   <div class="col-3 mx-3 mt-3">
    <h3>社員詳細</h3>
   </div>
 </div>
<div class="row">
  <div class="col-9">
    <div class="font-weight-bold lead col-6 my-3">
    登録情報 <%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-success px-3 mx-4" %>
    </div>
    <table class="table table-bordered" >
        <tr>
          <th class="table-active border-dark col-4">氏名</th>
          <td class="border-dark"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="table-active border-dark">メールアドレス</th>
          <td class="border-dark"><%= @user.email %></td>
        </tr>
    </table>
    <div class="font-weight-bold lead col-6 mt-4 mb-3">
      <table>
        <tr>
         <td>有給取得日数</td>
         <td></td>
         <td><%= @user.apply_paids.permited.count %>日</td>
        </tr>
        <tr>
         <td>残り日数</td>
         <td></td>
         <td>
           <%= @user.day-@user.apply_paids.permited.count %>日
         </td>
        </tr>
      </table>
    </div>
    </div>
    </div>
    </div>