config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  namespace :admin do
    resources :users , only: [:index, :show, :edit, :update, :destroy]
    resources :schedules, only: [:new, :index, :create, :show, :edit, :update, :destroy]
    resources :apply_paids, only: [:index, :show, :update]
  end
  namespace :public do
    resources :schedules, only: [:index, :show]
    resources :apply_paids, only: [:new, :index, :create, :show, :destroy]
    resources :users , only: [:index, :show, :edit, :update, :destroy]
  end
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply_paid.rb
class ApplyPaid < ApplicationRecord
  belongs_to :user
  belongs_to :schedule, optional: true
  enum apply_status: {waiting: 0, permited: 1, denied: 2}
  enum reason: {私用のため: 0, 体調不良: 1, その他: 2 }

  def get_color

    if self.apply_status_before_type_cast == 0
      #緑
      color = "#f0fff0"
    elsif self.apply_status_before_type_cast == 1
      color = "#adff2f"
    elsif self.apply_status_before_type_cast == 2
      color = "#ffff00"
    end
    color
  end

end

app/models/paid.rb
class Paid < ApplicationRecord
  belongs_to :user
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  enum event_status: {
      出勤日（申請可）: 0,
      出勤日（申請困難）: 1,
      出勤日（申請不可）: 2,
      休日: 3,
      有給推奨日: 4
  }
  def get_color

    if self.event_status_before_type_cast == 0
      #緑
      color = "#f0fff0"
    elsif self.event_status_before_type_cast == 1
      color = "#ffff00"
    elsif self.event_status_before_type_cast == 2
      color = "#800000"
    elsif self.event_status_before_type_cast == 3
      color = "#adff2f"
    elsif self.event_status_before_type_cast == 4
      color = "#00ffff"
    end
    color
  end

  has_many :apply_paids
  has_many :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :paid, dependent: :destroy
  has_many :apply_paids, dependent: :destroy
  has_many :schedules, dependent: :destroy


  accepts_nested_attributes_for :paid


end

app/controllers/admin/apply_paids_controller.rb
class Admin::ApplyPaidsController < ApplicationController
  def index
    @apply_paid = ApplyPaid.all
  end

  def show
    @apply_paid = ApplyPaid.find(params[:id])
  end

  def update
    @apply_paid = ApplyPaid.find(params[:id])
    #binding.pry
    if @apply_paid.update(apply_paid_params)
      redirect_to admin_apply_paids_path
    else
      render :show
    end
  end

  def apply_paid_params
    params.require(:apply_paid).permit(:apply_status)
  end

end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < ApplicationController
  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:notice] = "新しい予定を追加しました"
      redirect_to admin_schedules_path
    else
      @schedule = Schedule.all
      render :index
    end
  end

  def index
    @schedules = Schedule.all

  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      redirect_to admin_schedules_path
    else
      render :edit
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to admin_schedules_path, notice: "削除しました"
  end

  private

  def schedule_params
    params.require(:schedule).permit(:event_name, :start_time, :end_time, :event_status, :schedule_id)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   protected

    def after_sign_in_path_for(resource)
      admin_schedules_path
    end

    def after_sign_out_path_for(resource)
      new_admin_session_path
    end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :email, :day)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    public_schedules_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/apply_paid_helper.rb
module Admin::ApplyPaidHelper
end

app/helpers/admin/schedule_helper.rb
module Admin::ScheduleHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <header class="shadow-sm bg-light">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <a class="navbar-brand p-3 text-secondary">Work-Manager</a>
            <% if admin_signed_in? || user_signed_in? %>
             <button class="navbar-toggler reset-style" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
             </button>
            <% end %>

          <% if admin_signed_in? %>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto mt-1 ">
             <li class="nav-item mb-1 ml-3">
              <%= link_to "社員一覧", admin_users_path, class: 'nav-link text-dark btn btn-outline-dark' %></li>
             <li class="nav-item mb-1 ml-3">
              <%= link_to "予定一覧", admin_schedules_path, class: 'nav-link text-dark btn btn-outline-dark' %></li>
             <li class="nav-item mb-1 ml-3">
              <%= link_to '有給一覧', admin_apply_paids_path, class: 'nav-link text-dark btn btn-outline-dark' %></li>
　           <li class="nav-item mb-1 ml-3 ">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-dark' %></li>
            </ul>
            </div>
          <% end %>

          <% if user_signed_in? %>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav ml-auto mt-1 ">
              <li class="nav-item mb-1 ml-3">
              <%= link_to "マイページ", public_user_path(current_user), class: 'nav-link text-dark btn btn-outline-dark' %></li>
              <li class="nav-item mb-1 ml-3">
              <%= link_to '予定一覧', public_schedules_path, class: 'nav-link text-dark btn btn-outline-dark' %></li>
              <li class="nav-item mb-1 ml-3">
              <%= link_to "有休一覧", public_apply_paids_path, class: 'nav-link text-dark btn btn-outline-dark' %></li>
　            <li class="nav-item ml-3 ">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-dark' %></li>
             </ul>
            </div>
          <% end %>


      </nav>
    </header>
      <%= yield %>
      <footer class="border fixed-bottom bg-light">
        <p class="text-dark text-center pt-3">©Portfolio</p>
      </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day),style: "background-color: #{sorted_events[day][0]&.get_color}" do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>

            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>